name: ssh-into-aws-ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  Deploy:
    # The type of runner that the job will run on
    runs-on: 
      - self-hosted
#      - label-1
    steps:
#      - name: Say Hello World
#        run: echo Hello, world!

#      - name: git clone
#        env:
#          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#        run: cd /var/www/html/ && sudo git clone "https://"$ACCESS_TOKEN"@github.com/FarazAshfaq/github-ci-cd-self-runner.git"
       - name: move data and swtich user
         run: |
           sudo su
           whoami
           cd /var/www/html/
