name: ssh-into-aws-ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  Deploy:
    # The type of runner that the job will run on
    runs-on: 
      - self-hosted
#      - label-1
    steps:
#      - name: Say Hello World
#        run: echo Hello, world!

#      - name: git clone
#        env:
#          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#        run: cd /var/www/html/ && sudo git clone "https://"$ACCESS_TOKEN"@github.com/FarazAshfaq/github-ci-cd-self-runner.git"
       - name: move data and swtich user
         run: |
#           su - root
           whoami
           cd /var/www/html/
       - name: Send skype
         uses: Eloco/docker-action-send-skype@v2
         with:
           # Required skype username:
           skype_username : ${{ secrets.SKYPE_USERNAME }}
           # Required skype password:
           skype_password : ${{ secrets.SKYPE_PASSWORD }}
           # Required skype_ids(both user_id  group_id) which u want to send to [also support multiple id which connect by space]
           skype_ids      : live:.cid.66b3153ed0badf0a@thread.skype
           # Optional (recommended): the path of message file or message file's folder [support emoji]
           send_msg_path  : msg.txt
           # Optional (recommended): the path of attach file or attach file's folder 
           send_file_path : download/
