name: ssh-into-aws-ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: 
      - self-hosted
      - label-1
    steps:
      - name: Say Hello World
        run: echo Hello, world!
      - name: install nginx
        run: apt install nginx -y
      - name: list direcotry
        run: cd /var/www/html && ls -la
