name: ssh-into-aws-ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  Deploy:
    # The type of runner that the job will run on
    runs-on: 
      - self-hosted
#      - label-1
    steps:
#      - name: Say Hello World
#        run: echo Hello, world!
#      - name: install nginx
#        run: sudo apt install nginx -y
#      - name: git pull
#        run: cd /var/www/html && sudo git pull
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Preparing blueprint-environment'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: https://github.com/FarazAshfaq/github-ci-cd-self-runner.git
          path: /var/www/html/
